INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (1, 'Algeria - Algerian Dinar', 'DZD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (2, 'Angolan new kwanza', 'AON');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (3, 'Argentina - Argetine Peso', 'ARS');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (4, 'Australia - Austrlian Dollar', 'AUD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (5, 'Bahraini Dinar', 'BHD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (6, 'Bangladesh - Bangladeshi Taka', 'BDT');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (7, 'Barbados - Barbados Dollars', 'BBD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (8, 'Belorussian Ruble', 'BYR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (9, 'Brazil - Brazilian Real', 'BRL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (10, 'Bulgaria - Bulgarian Leva', 'BGL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (11, 'CFA Franc', 'XOF');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (12, 'Canada - Canadian Dollar', 'CAD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (13, 'Chile - Chilean Peso', 'CLP');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (14, 'China - Yuan Renminbi', 'CNY');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (15, 'Colombia - Colombian Pesos', 'COP');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (16, 'Costa Rica - Costa Rican Colon', 'CRC');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (17, 'Croatia - Croatian Kuna', 'HRK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (18, 'Cyprus - Cyprus Pound', 'CYP');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (19, 'Czech Republic - Czech Koruna', 'CZK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (20, 'D.R.C Congo - Congolese Franc', 'CDF');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (21, 'Denmark - Danish Krone', 'DKK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (22, 'Djibouti Franc', 'DJF');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (23, 'Dominican - Dominican Peso', 'DOP');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (24, 'Egyp - Egyptian Pound', 'EGP');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (25, 'Eritrea - Eritrean Nakfa', 'ERN');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (26, 'Estonian Krone', 'EEK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (27, 'Euro', 'EUR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (28, 'Fiji - Fiji Dollar', 'FJD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (29, 'Georgia - Georgian Lari', 'GEL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (30, 'Ghana - Ghanian Cedi', 'GHC');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (31, 'Guatemala - Guetemala Quetzal', 'GTQ');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (32, 'Guyana - Guyana Dollars', 'GYD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (33, 'Honduras - Honduras Dollar', 'HNL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (34, 'Hong Kong - Hong Kong Dollar', 'HKD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (35, 'Hungary - Hungarian Forint', 'HUF');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (36, 'India - Indian Rupee', 'INR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (37, 'Indonesia - Indonesian Rupiah', 'IDR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (38, 'Iran - Iranian Rial', 'IRR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (39, 'Isreal - New Israeli Sheqel', 'ILS');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (40, 'Jamaica - Jamaican Dollar', 'JMD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (41, 'Japan - Japanese Yen', 'JPY');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (42, 'Jordanian Dinars', 'JOD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (43, 'Kazakhstani Tenge', 'KZT');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (44, 'Kenya - Kenyan Shilling', 'KES');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (45, 'Korea - Korean Won', 'KRW');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (46, 'Latvia - Latvian Lat', 'LVL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (47, 'Libya - Libya Dinars', 'LYD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (48, 'Lithuanian Lita', 'LTL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (49, 'Malawi - Malawi Kwacha', 'MWK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (50, 'Malaysia - Malaysian Ringgit', 'MYR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (51, 'Malta - Maltese Lira', 'MTL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (52, 'Mauritius - Mauritius Rupee', 'MUR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (53, 'Mexico - Mexican New Peso', 'MXN');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (54, 'Moldova LEU', 'MDL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (55, 'Moroccan Dirham', 'MAD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (56, 'Mozambique - Mozambique Meticais', 'MZN');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (57, 'Nepal - Nepalese Rupee', 'NPR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (58, 'New Zealand - New Zealand Dollar', 'NZD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (59, 'Nicaragua - Nicaragua Cordobas', 'NIO');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (60, 'Nigeria - Nigerian Naira', 'NGN');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (61, 'Norway - Norwegian Krone', 'NOK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (62, 'Pakistan - Pakistan Rupee', 'PKR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (63, 'Panama - Panama Balboa', 'PAB');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (64, 'Papa New Guineau - Papa New Guineau Kina', 'PGK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (65, 'Paraguay - Paraguay Guarani', 'PYG');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (66, 'Peru - Peru Nuevo Sol', 'PEN');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (67, 'Phillippines - Philippine Peso', 'PHP');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (68, 'Poland - Polish Zloty', 'PLN');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (69, 'Republic of Congo - CFA Franc', 'XAF');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (70, 'Romania - Romanian Lei', 'RON');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (71, 'Russia - Russian Ruble', 'RUR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (72, 'Rwanda - Rwandan Franc', 'RWF');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (73, 'Serbia - Serbian Dinars', 'CSD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (74, 'Siera Leone - Leone', 'SLL');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (75, 'Singapore - Singapore Dollar', 'SGD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (76, 'Solomon Islands - Solomon Islands Dollar', 'SBD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (77, 'South Africa - South African Rand', 'ZAR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (78, 'Sri Lanka - Sri Lanka Rupee', 'LKR');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (79, 'Suridescription1 - Suridescription1 Dollars', 'SRD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (80, 'Sweden - Swedish Krona', 'SEK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (81, 'Switzerland - Swiss Franc', 'CHF');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (82, 'Taiwan - New Taiwan Dollar', 'TWD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (83, 'Tanzania - Tanzanian Shilling', 'TZS');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (84, 'Thailand - Thai Baht', 'THB');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (85, 'Trinidad & Tobago - Dollars', 'TTD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (86, 'Turkey - Turkish Lira', 'TRY');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (87, 'UK - Pound Sterling', 'GBP');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (88, 'US - US Dollar', 'USD');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (89, 'Uganda - Uganda Shilling', 'UGX');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (90, 'Ukraine - Ukrainian Hryvnia', 'UAH');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (91, 'United Arab Emirates - Dirham', 'AED');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (92, 'Uruguay - Uruguay Pesos', 'UYU');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (93, 'Uzbekistan - Uzbekistan Sum', 'UZS');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (94, 'Venezuela - Venezuelan Bolivar', 'VEF');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (95, 'Vietnam - Vietdescription1se Dong', 'VND');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (96, 'Western Samoa - Western Samoa Tala', 'WST');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (97, 'Yemen - Yemeni Rial', 'YER');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (98, 'Zambia - Zambian Kwacha', 'ZMK');
INSERT INTO grailCurrencyFields(id, "description", "name") VALUES (99, 'Zimbabwe - Zimbabwe Dollar', 'ZWD');