CREATE TABLE grailendmarketfields
(
  id bigint NOT NULL,
  name character varying(255) NOT NULL,
  region bigint NOT NULL
)

INSERT INTO grailendmarketfields(id, "name", region) VALUES (1, 'Abu Dhabi', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (2, 'Afghanistan', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (3, 'Africa & Mid East GTR', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (4, 'Albania', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (5, 'Algeria', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (6, 'Americas GTR', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (7, 'Andorra', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (8, 'Angola', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (9, 'Anguilla', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (10, 'Antarctica', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (11, 'Antigua', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (12, 'Argentina', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (13, 'Armenia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (14, 'Aruba', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (15, 'Ascension Islands', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (16, 'Asia Pacific GTR', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (17, 'Asia Pacific North Exports', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (18, 'Australia', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (19, 'Austria', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (20, 'Azerbaijan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (21, 'Azores', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (22, 'Bahamas', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (23, 'Bahrain', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (24, 'Bangladesh', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (25, 'Barbados', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (26, 'Belarus', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (27, 'Belgium', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (28, 'Belize', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (29, 'Benin', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (30, 'Bermuda', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (31, 'Bhutan', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (32, 'Bolivia', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (33, 'Bosnia Federation', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (34, 'Botswana', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (35, 'Brazil', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (36, 'Brunei', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (37, 'Bulgaria', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (38, 'Burkina Faso', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (39, 'Burundi', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (40, 'Cambodia', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (41, 'Cameroon', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (42, 'Canada', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (43, 'Canary Islands', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (44, 'Cape Verde Islands', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (45, 'Cayman Islands', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (46, 'Cent-Afr.Rep.', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (47, 'Ceuta & Melilla', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (48, 'Chad', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (49, 'Chile', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (50, 'China', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (51, 'Cocos Island', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (52, 'Colombia', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (53, 'Congo', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (54, 'Congo Democratic Rep', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (55, 'Cook Isles', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (56, 'Corsica', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (57, 'Costa Rica', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (58, 'Croatia', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (59, 'Cuba', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (60, 'Cyprus', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (61, 'Cyprus (North)', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (62, 'Czech Republic', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (63, 'Denmark', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (64, 'Djibouti', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (65, 'Dominica', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (66, 'Dominican Republic', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (67, 'Dubai', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (68, 'East Congo', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (69, 'East Europe GTR', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (70, 'East Samoa', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (71, 'Ecuador', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (72, 'Egypt', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (73, 'El Salvador', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (74, 'Equatorial Guinea', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (75, 'Eritrea', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (76, 'Estonia', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (77, 'Ethiopia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (78, 'Falkland Is.', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (79, 'Faroe Isles', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (80, 'Fiji', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (81, 'Finland', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (82, 'Fr Oceania', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (83, 'Fr Polynesia', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (84, 'France', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (85, 'French Guiana', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (86, 'Gabon', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (87, 'Gambia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (88, 'Georgia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (89, 'Germany', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (90, 'Ghana', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (91, 'Gibraltar', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (92, 'Greece', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (93, 'Greenland', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (94, 'Grenada', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (95, 'Guadeloupe', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (96, 'Guam', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (97, 'Guatemala', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (98, 'Guernsey', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (99, 'Guinea', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (100, 'Guinea Bissau', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (101, 'Guyana', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (102, 'Haiti', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (103, 'Honduras', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (104, 'Hong Kong', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (105, 'Hungary', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (106, 'Iceland', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (107, 'Independent Comores', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (108, 'India', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (109, 'Indonesia', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (110, 'Iran', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (111, 'Iraq', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (112, 'Ireland', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (113, 'Irian Jaya', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (114, 'Israel', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (115, 'Italy', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (116, 'Ivory Coast', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (117, 'Jamaica', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (118, 'Japan', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (119, 'Jersey', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (120, 'Jordan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (121, 'Kazakhstan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (122, 'Kenya', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (123, 'Kiribati Isl.', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (124, 'Kosovo', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (125, 'Kuwait', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (126, 'Kyrgyzstan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (127, 'Langkawi/Labuan', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (128, 'Laos', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (129, 'Latvia', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (130, 'Lebanon', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (131, 'Lesotho', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (132, 'Levant (Misc)', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (133, 'Liberia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (134, 'Libya', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (135, 'Liechtenstein', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (136, 'Line Isles', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (137, 'Lithuania', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (138, 'Luxembourg', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (139, 'Macao', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (140, 'Macedonia', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (141, 'Madagascar', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (142, 'Madeira', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (143, 'Malawi', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (144, 'Malaysia', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (145, 'Maldive Isles', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (146, 'Mali', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (147, 'Malta', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (148, 'Martinique', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (149, 'Mauritania', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (150, 'Mauritius', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (151, 'Mayotte Comores', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (152, 'Mexico', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (153, 'Misc./Europe', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (154, 'Moldova', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (155, 'Monaco', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (156, 'Mongolia', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (157, 'Montenegro', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (158, 'Montserrat', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (159, 'Morocco', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (160, 'Mozambique', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (161, 'Myanmar', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (162, 'N Caledonia', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (163, 'Namibia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (164, 'Nauru', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (165, 'Nepal', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (166, 'Neth. Antilles', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (167, 'Netherlands', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (168, 'New Zealand', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (169, 'Nicaragua', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (170, 'Niger', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (171, 'Nigeria', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (172, 'Niue Island', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (173, 'Norfolk Island', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (174, 'North Korea', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (175, 'Norway', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (176, 'Ocean Island', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (177, 'Oman', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (178, 'Pakistan', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (179, 'Palestine', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (180, 'Panama', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (181, 'Panama Canal', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (182, 'Papua N G', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (183, 'Paraguay', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (184, 'Peru', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (185, 'Philippines', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (186, 'Poland', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (187, 'Portugal', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (188, 'Puerto Rico', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (189, 'Qatar', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (190, 'Reunion', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (191, 'Romania', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (192, 'Russia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (193, 'Rwanda', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (194, 'San Marino', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (195, 'Sao Tome & Principe', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (196, 'Saudi Arabia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (197, 'Senegal', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (198, 'Serbia', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (199, 'Seychelles', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (200, 'Sierra Leone', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (201, 'Singapore', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (202, 'Singapore Operations', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (203, 'Slovakia', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (204, 'Slovenia', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (205, 'Solomon Isles', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (206, 'Somalia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (207, 'Somaliland', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (208, 'South Africa', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (209, 'South Korea', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (210, 'South Sudan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (211, 'Spain', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (212, 'Sri Lanka', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (213, 'St.Helena', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (214, 'St.Kitts', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (215, 'St.Lucia', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (216, 'St.Martin', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (217, 'St.Vincent', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (218, 'Sudan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (219, 'Suriname', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (220, 'Svalbard', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (221, 'Swaziland', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (222, 'Sweden', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (223, 'Switzerland', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (224, 'Syria', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (225, 'Taiwan', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (226, 'Tajikistan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (227, 'Tanzania', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (228, 'Thailand', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (229, 'Timor', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (230, 'Togo', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (231, 'Tonga Isles', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (232, 'Trinidad & Tobago', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (233, 'Tunisia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (234, 'Turkey', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (235, 'Turkmenistan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (236, 'Turks & Caicos Is.', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (237, 'Tuvalu', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (238, 'U.K.', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (239, 'U.S.A.', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (240, 'Uganda', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (241, 'Ukraine', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (242, 'United Arab Emirates', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (243, 'Uruguay', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (244, 'Uzbekistan', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (245, 'Vanuatu', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (246, 'Venezuela', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (247, 'Vietnam', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (248, 'Virgin Is.- British', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (249, 'Virgin Is.- US', 1);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (250, 'Wallis & Fatuna', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (251, 'West Europe GTR', 4);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (252, 'West Samoa', 2);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (253, 'Western Sahara', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (254, 'Yemen (Arab Rep)', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (255, 'Zambia', 3);
INSERT INTO grailendmarketfields(id, "name", region) VALUES (256, 'Zimbabwe', 3);
